### ISSUE TITLE
可以改为 ahk 1.1版本的吗

### ISSUE THREAD

**Issue by YIRU69** [livelycode36/markdown2potplayer#1]
感谢大大的开放，我一直在用quicker 来达成这个效果，能力不足，终于看到你能开发这个功能

我现在在用 ahk 1.1 版本的，请问大大可以弄一个1.1版本的吗

**Comment by livelycode36** [comment]
我也是这两天刚学的，我试试能不能用ai快速的转为1.1版本😄

**Comment by YIRU69** [comment]
太厉害了，两天刚学就写了个程序

**Comment by YIRU69** [comment]
1.1版本和2.0版本可以一起使用，不干扰
