### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by cannibalox** [livelycode36/markdown2potplayer#10]
hey, noticed a couple of typos, maybe you want to correct them ?

### in TemplateParser.ahk : 
* `tempALtes` should be `tempLAtes`

### in Gui.ahk :
* l26: `maKRdown` should be `maRKdown` 
* l29: `Edit_image_tempALte ` should be `Edit_image_tempLAte`

### in GuiControl.ahk 
* l32-33: `maKRdown` should be `maRKdown` 
* l36-37: `tempALte` should be `tempLAte`

**Comment by livelycode36** [comment]
Yes, you're right, thank you!!
