### ISSUE TITLE
license

### ISSUE THREAD

**Issue by cannibalox** [livelycode36/markdown2potplayer#11]
hey, do you mind adding a license for this repo ?
is it MIT license ?
I forked your repo to make an english translation, hope you don't mind !

**Comment by livelycode36** [comment]
Of course the MIT license is what I intended

My English is not good, thank you for your work, now it should help more people!

**Comment by livelycode36** [comment]
Support multi-language now

There is the language code here: [LCID.ahk](https://github.com/livelycode36/markdown2potplayer/blob/main/lib/gui/i18n/LCID.ahk)
This is an example
- [en-US.ini](https://github.com/livelycode36/markdown2potplayer/blob/main/lib/gui/i18n/en-US.ini)

**Note: Please use the system default ANSI encoding for .ini files!**
I did my best😄
