### ISSUE TITLE
关于markdown 语法的bug

### ISSUE THREAD

**Issue by jiangnanqw12** [livelycode36/markdown2potplayer#12]
hello,
```
视频 [📺](jv://open?path=jv://open?path=C%3A%5C1709639118.mp4&time=01:02-02:06 "01:02-02:06")
```
"01:02-02:06" 做为markdown提示的一部分,如果在potplayer关闭的情况下,会出现报错.
![image](https://github.com/livelycode36/markdown2potplayer/assets/41460494/8200d21a-4c6d-4696-b214-ae6ea918fcf8)
▶	1128: If (InStr(WinGetTitle("ahk_id " hwnd),video_name) && (potplayer.GetPlayStatus() == "Running"))

如果先打开如下链接:
```
视频 [📺](jv://open?path=jv://open?path=C%3A%5C1709639118.mp4&time=02-02:00),
```
链接
```
视频 [📺](jv://open?path=jv://open?path=C%3A%5C1709639118.mp4&time=01:02-02:06 "01:02-02:06")
```
就能正常工作

**Comment by jiangnanqw12** [comment]
hello,
视频 [📺](jv://open?path=jv://open?path=C%3A%5C1709639118.mp4&time=01:02-02:06 "01:02-02:06")
"01:02-02:06" 做为markdown提示的一部分,如果在potplayer关闭的情况下,会出现报错.
![image](https://github.com/livelycode36/markdown2potplayer/assets/41460494/8200d21a-4c6d-4696-b214-ae6ea918fcf8)
▶	1128: If (InStr(WinGetTitle("ahk_id " hwnd),video_name) && (potplayer.GetPlayStatus() == "Running"))

如果先打开如下链接:
视频 [📺](jv://open?path=jv://open?path=C%3A%5C1709639118.mp4&time=02-02:00),

链接
视频 [📺](jv://open?path=jv://open?path=C%3A%5C1709639118.mp4&time=01:02-02:06 "01:02-02:06")
就能正常工作

**Comment by livelycode36** [comment]
`-`后面的部分是结束时间，例如`time=01:02-02:06`结束时间 `02:06`
但是此时间戳`time=01:02-02:06 "01:02-02:06"`的结束时间是 `02:06 "01:02-02:06"`，程序解析时间会错误

**"01:02-02:06" 做为markdown提示的一部分** <-- 可以在标题提示时间呀

---
**1128: If (InStr(WinGetTitle("ahk_id " hwnd),video_name) && (potplayer.GetPlayStatus() == "Running"))**
这个错误，最新版应该是没有了，哥们是最新版吗？

**Comment by jiangnanqw12** [comment]
> `-`后面的部分是结束时间，例如`time=01:02-02:06`结束时间 `02:06` 但是此时间戳`time=01:02-02:06 "01:02-02:06"`的结束时间是 `02:06 "01:02-02:06"`，程序解析时间会错误
> 
> **"01:02-02:06" 做为markdown提示的一部分** <-- 可以在标题提示时间呀
> 
> **1128: If (InStr(WinGetTitle("ahk_id " hwnd),video_name) && (potplayer.GetPlayStatus() == "Running"))** 这个错误，最新版应该是没有了，哥们是最新版吗？

最新版是没有了, sorry
没有pull
