### ISSUE TITLE
帮助

### ISSUE THREAD

**Issue by TheGodOfKing** [livelycode36/markdown2potplayer#13]
你好，我是JumpVideo的创始人，主程序现在跑了，软件没人接手，如果大佬愿意，希望能合作。

**Comment by livelycode36** [comment]
喵喵喵？？？发生什么事了

**Comment by TheGodOfKing** [comment]
@livelycode36 [为原创发声！软件创始人遭遇背叛！！源码被删](https://www.bilibili.com/video/BV1Px4y1Q7is/?vd_source=793a152a25049e575a5f472546cd09a7) 请看这个视频

**Comment by livelycode36** [comment]
- [你的说法](https://www.bilibili.com/video/BV1Px4y1Q7is)
- [他的说法](https://www.yuque.com/zhangyewuxianxiaozhang/er8rsh/huntnk8a9me4iegn)

1. 我也不好说对错，目前中立吧，观望后续
2. 如果软件已经用不了，本地视频可以改一下连接，这样本项目就可以让你的用户继续使用了，放心本项目纯本地，不会窃取数据。算是解一下燃眉之急

**Comment by YIRU69** [comment]
他们纯粹就是为了利益而发生的矛盾，本来就是分享知识的东西，掺杂利益就会变味。
