### ISSUE TITLE
请问支持毫秒吗

### ISSUE THREAD

**Issue by C21H21NO2S** [livelycode36/markdown2potplayer#15]
如题，我用精准到毫秒的字幕文本批处理成时间戳，发现很多时间戳会提前结束，不知道是不是后面的毫秒不播放了

**Comment by livelycode36** [comment]
potplayer支持毫秒的，我在时间处理的时候使用了秒，而不是毫秒，确实不够合理，我改一下

**Comment by C21H21NO2S** [comment]
谢谢，再请教个事，不知道是不是potplayer的原因，同一个音频，跳转其他时间戳时，会比原来的时间戳提前一点点，时不时会播放前一个字幕的结尾的地方。我用字幕软件看字幕块和音频波形图，字幕块的时间戳是精准没有错位的。

ps: 用时间戳全新启动potplayer第一次播放没有上面说的问题。

livelycode ***@***.***> 于 2024年3月21日周四 07:03写道：

**Comment by livelycode36** [comment]
大概和这个有关？[时间跨度](https://github.com/livelycode36/markdown2potplayer#potplayer%E5%BF%AB%E6%8D%B7%E6%8E%A7%E5%88%B6)

据我观察，不关闭【时间跨度-以关键帧为移动单位】的情况下，potplayer会`后处理`时间戳，导致你的这种情况，你关闭该选项，然后再试一下，看看是否有效

**Comment by C21H21NO2S** [comment]
> 大概和这个有关？[时间跨度](https://github.com/livelycode36/markdown2potplayer#potplayer%E5%BF%AB%E6%8D%B7%E6%8E%A7%E5%88%B6)
> 
> 据我观察，不关闭【时间跨度-以关键帧为移动单位】的情况下，potplayer会`后处理`时间戳，导致你的这种情况，你关闭该选项，然后再试一下，看看是否有效

这个一直没有开启

**Comment by livelycode36** [comment]
那可能还是毫秒丢失了，一会更新一下

**Comment by livelycode36** [comment]
哥们试试[0.2.2](https://github.com/livelycode36/markdown2potplayer/releases/tag/0.2.2)，应该不会丢失毫秒。

`同一个音频，跳转其他时间戳时，会比原来的时间戳提前一点点，时不时会播放前一个字幕的结尾的地方` 这个问题，不懂是不是毫秒的原因，辛苦你也试一下

**Comment by C21H21NO2S** [comment]
> 哥们试试[0.2.2](https://github.com/livelycode36/markdown2potplayer/releases/tag/0.2.2)，应该不会丢失毫秒。
> 
> `同一个音频，跳转其他时间戳时，会比原来的时间戳提前一点点，时不时会播放前一个字幕的结尾的地方` 这个问题，不懂是不是毫秒的原因，辛苦你也试一下

嗯嗯，现在时间戳开始的地方没有重叠了，但结尾延长了，在字幕软件上看时间线是没问题的，发你素材，麻烦帮忙看一下，谢谢。[05_The Haunting of Hajji Hotak - Jamil Jan Kochai.zip](https://github.com/livelycode36/markdown2potplayer/files/14681225/05_The.Haunting.of.Hajji.Hotak.-.Jamil.Jan.Kochai.zip)

![image](https://github.com/livelycode36/markdown2potplayer/assets/80377040/8d11b4ca-b9a1-4e74-9a95-1835f8bbfebf)

```
41. [00:07:59](jv://open?path=路径名称&time=00:07:59.540-00:08:02.740) It's really a tragedy, you think.
42. [00:08:02](jv://open?path=路径名称&time=00:08:02.740-00:08:05.260) She could have been a fine spy.
43. [00:08:05](jv://open?path=路径名称&time=00:08:05.260-00:08:10.940) In the end, Lily confessed her sin to Mary, who immediately mocked her.
44. [00:08:10](jv://open?path=路径名称&time=00:08:10.940-00:08:12.860) “idiot,” she said.
45. [00:08:12](jv://open?path=路径名称&time=00:08:12.860-00:08:14.780) “You're short enough as it is.
46. [00:08:14](jv://open?path=路径名称&time=00:08:14.780-00:08:17.460) How do you expect to get taller without protein?”
47. [00:08:17](jv://open?path=路径名称&time=00:08:17.460-00:08:19.580) “I'll eat beans.”
48. [00:08:19](jv://open?path=路径名称&time=00:08:19.580-00:08:20.900) “Beans?
49. [00:08:20](jv://open?path=路径名称&time=00:08:20.900-00:08:22.100) How many beans?
50. [00:08:22](jv://open?path=路径名称&time=00:08:22.100-00:08:26.300) This room isn't ventilated enough for you to be eating beans all day.”
51. [00:08:26](jv://open?path=路径名称&time=00:08:26.300-00:08:29.060) “please,” Lily said.
52. [00:08:29](jv://open?path=路径名称&time=00:08:29.060-00:08:30.180) “don't tell.”
53. [00:08:30](jv://open?path=路径名称&time=00:08:30.180-00:08:38.500) Mary laughed and promised to snitch as soon as she could, which was a lie, of course, because Mary wasn't the sort.

```

**Comment by livelycode36** [comment]
**结尾延长**
`结尾延长`的原因是：程序采用轮询的方式对比当前播放时间，然后超出范围就暂停的，出于性能考虑，默认是1秒，对比一次，包括视频开始的情况也是如此。所以你这里的情况就是`结尾延长`


解决也简单，我可以给你一个选项，你自定义轮询的时间，想要结尾准确就设置时间低一些

图上的字幕软件是啥？看着还不错嗷

**Comment by C21H21NO2S** [comment]
> **结尾延长** `结尾延长`的原因是：程序采用轮询的方式对比当前播放时间，然后超出范围就暂停的，出于性能考虑，默认是1秒，对比一次，包括视频开始的情况也是如此。所以你这里的情况就是`结尾延长`
> 
> 解决也简单，我可以给你一个选项，你自定义轮询的时间，想要结尾准确就设置时间低一些
> 
> 图上的字幕软件是啥？看着还不错嗷

谢谢解答，但不太懂，不过能精准结束就行。外语听力时比较需要精准的时间戳，时不时听到别的词体验不太好。 
字幕软件是 https://www.nikse.dk/subtitleedit

**Comment by livelycode36** [comment]
下午在忙，刚才又更新了，还是0.2.2，你下载试试，这个值越低，结尾的暂停越准确，我使用100左右，基本上无拖尾了
![image](https://github.com/livelycode36/markdown2potplayer/assets/57926220/3be6a6c2-01c4-4844-a649-7f7ad68d9449)

**Comment by C21H21NO2S** [comment]
> 下午在忙，刚才又更新了，还是0.2.2，你下载试试，这个值越低，结尾的暂停越准确，我使用100左右，基本上无拖尾了 ![image](https://private-user-images.githubusercontent.com/57926220/315244016-3be6a6c2-01c4-4844-a649-7f7ad68d9449.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMzIzMDAsIm5iZiI6MTcxMTAzMjAwMCwicGF0aCI6Ii81NzkyNjIyMC8zMTUyNDQwMTYtM2JlNmE2YzItMDFjNC00ODQ0LWE2NDktN2Y3YWQ2OGQ5NDQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDE0NDAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyODEyMzMwMGI4ZjBmODM4NmU3ZjlmNjRkODA1MjU1YzkxMDQ5OWIzNDg2YWVjZWFmYTIzZGY5ZDhkMjU0Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._Twdgjf1NnosKhWcVDMsABlnYYSDxVMi6PVpzIK0bQs)

好的，我试试，非常感谢

**Comment by C21H21NO2S** [comment]
> 下午在忙，刚才又更新了，还是0.2.2，你下载试试，这个值越低，结尾的暂停越准确，我使用100左右，基本上无拖尾了 ![image](https://private-user-images.githubusercontent.com/57926220/315244016-3be6a6c2-01c4-4844-a649-7f7ad68d9449.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMzIzMDAsIm5iZiI6MTcxMTAzMjAwMCwicGF0aCI6Ii81NzkyNjIyMC8zMTUyNDQwMTYtM2JlNmE2YzItMDFjNC00ODQ0LWE2NDktN2Y3YWQ2OGQ5NDQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDE0NDAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyODEyMzMwMGI4ZjBmODM4NmU3ZjlmNjRkODA1MjU1YzkxMDQ5OWIzNDg2YWVjZWFmYTIzZGY5ZDhkMjU0Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._Twdgjf1NnosKhWcVDMsABlnYYSDxVMi6PVpzIK0bQs)

可以了，谢谢 ❤❤

**Comment by livelycode36** [comment]
okk~
