### ISSUE TITLE
图片回链模板在思源笔记中的显示效果

### ISSUE THREAD

**Issue by UserZYF** [livelycode36/markdown2potplayer#16]
经过在思源笔记和Obsidian中尝试图片回链，如果图片回链模板为
```
{title}
{image}
```
![Snipaste_2024-03-22_00-18-47](https://github.com/livelycode36/markdown2potplayer/assets/38289979/adab9183-d84e-4d78-a26a-e4955b53399c)
在Obsidian中可以实现链接和图片上下换行

但在思源笔记中，则会显示在一行中，经过各种尝试也不能达到预期效果
![最下边鼠标选中区域](https://github.com/livelycode36/markdown2potplayer/assets/38289979/5b52ff23-6bec-4b50-9684-914114ce3458)
也许是思源笔记类似于Notion的`块`的特性，导致这种差异
如果想要在思源笔记中实现Obsidian中链接和图片强制换行的效果，请问是否有相关的符号可以实现呢

**Comment by livelycode36** [comment]
可以换个思路，既然兼容markdown语法，markdown语法是可以使用html的，你可以这样
```
{title}<br/>
{image}

```
![image](https://github.com/livelycode36/markdown2potplayer/assets/57926220/693f0d5e-db93-4eb4-a667-08c929045e7a)

**Comment by UserZYF** [comment]
果然可以！！！感谢🙏🏻
很好用



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月22日(周五) 中午1:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [livelycode36/markdown2potplayer] 图片回链模板在思源笔记中的显示效果 (Issue #16)




 
可以换个思路，既然兼容markdown语法，markdown语法是可以使用html的，你可以这样
 {title}<br/&gt; {image}  
image.png (view on web)

**Comment by livelycode36** [comment]
客气，记得点star
