### ISSUE TITLE
同时点击不同视频的回链，只会在当前视频中跳转

### ISSUE THREAD

**Issue by UserZYF** [livelycode36/markdown2potplayer#17]
- 对象：在线视频A和在线视频B
- 软件：potplayer 思源笔记
- 版本：0.2.1

### 问题描述
假如目前文档中（可以是同一文档，或者是不同文档）同时有A视频和B视频的回链，点击A视频回链，软件会打开potplayer播放A视频并定位到相应时间戳；
但此时点击B视频回链时，不会跳转到B视频对应时间戳，而是会跳转至同时间A视频对应时间戳。

### 个人疑惑
不知道是否是potplayer设置问题，（此现象在Obsidian软件中可以复现）

### 补充反馈
另：反馈一个不成问题的问题
当时间戳时间不满一分钟时，以17秒举例： {time}会显示17，而不是00:17，时间戳含义不明显。

**Comment by livelycode36** [comment]
- 跳转到同一视频吗？方便给我视频A、B的时间戳吗
- ` {time}会显示17，而不是00:17`这里[调整时间的格式](https://github.com/livelycode36/markdown2potplayer#%E8%B0%83%E6%95%B4%E6%97%B6%E9%97%B4%E7%9A%84%E6%A0%BC%E5%BC%8F)可以设置为`00:17`

**Comment by UserZYF** [comment]
就是两个视频共用一个时间刻度，应该是任意两个不同的视频都能复现，如有需要，明天录制个视频😁



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月23日(周六) 凌晨0:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [livelycode36/markdown2potplayer] 同时点击不同视频的回链，只会在当前视频中跳转 (Issue #17)




  
跳转到同一视频吗？方便给我视频A、B的时间戳吗
 
 {time}会显示17，而不是00:17这里调整时间的格式可以设置为00:17

**Comment by livelycode36** [comment]
好了 0.2.3 修复嘞
