### ISSUE TITLE
在使用获取视频+图片快捷键后，使用Picgo粘贴图片并上传到Vika图床时报错. 图床本身配置正常，手动粘贴截图没问题. 

### ISSUE THREAD

**Issue by mdsnalw** [livelycode36/markdown2potplayer#19]
报错信息如下：
- 
![image](https://github.com/livelycode36/markdown2potplayer/assets/57386018/99037d11-7cd5-4ecd-af21-07dab0483606)
报错提示：
图片: ⚠️upload failed, check dev console

不使用图片+视频回链获取快捷键，手动截图，并粘贴到markdown，图床运行正常：
- 
![image](https://github.com/livelycode36/markdown2potplayer/assets/57386018/5bb92ed0-31f9-4940-abe7-bb75e9008845)

软件上的模板和快捷键设置：
- 
![image](https://github.com/livelycode36/markdown2potplayer/assets/57386018/825185b4-8afe-4115-bf6c-5e5340f745bf)

Console报错信息：
- 
![image](https://github.com/livelycode36/markdown2potplayer/assets/57386018/ceeaecc8-14d8-4f76-ba29-d559305b519b)

**Comment by livelycode36** [comment]
明天我在瞅瞅

**Comment by livelycode36** [comment]
使用这个看看：[Release 0.2.4](https://github.com/livelycode36/markdown2potplayer/releases/tag/0.2.4)
这里调整为 `3000`左右，我这里亲测可以
![image](https://github.com/livelycode36/markdown2potplayer/assets/57926220/9ab51150-42c9-4859-9b03-0e709847621d)

**Comment by mdsnalw** [comment]
感谢大神的耐心解答! 还特地为此开发了一个新的版本迭代. 
目前我在新版本上，有针对性地调整了图片粘贴延迟后，上传图片到图床没有报错了~
![image](https://github.com/livelycode36/markdown2potplayer/assets/57386018/4c1b6123-6d89-4f9e-a64d-2839cfe35ffc)
另外，想请教下，这个延迟时间的设置，是为了提升图片上传的冗余时间，从而提高容错率吗？我是否可以再降低下延迟时间？如设置为1500-2500左右，以提升图片上传时效？（目前在家上班，连接公司VPN，可能没办法做太多对比测试）
![image](https://github.com/livelycode36/markdown2potplayer/assets/57386018/2ca38a70-2a43-443f-b629-579e2bced3a6)

**Comment by livelycode36** [comment]
你说的完全正确！可以调低延迟，具体多少延迟，毕竟每个人网络环境不同嘛，需要自己测试一下😁

**Comment by mdsnalw** [comment]
感谢感谢~！确实是这样的，需要根据网络情况做参数微调. 反正就根据报错时再做调整就好了 哈哈
