### ISSUE TITLE
使用问题，在回调 potplayer 播放器，一直显示“请提供至少一个参数”

### ISSUE THREAD

**Issue by YIRU69** [livelycode36/markdown2potplayer#2]
如题，我按照说明进行了操作，到时还是出现了“请提供至少一个参数”的问题，请问是什么原因

**Comment by YIRU69** [comment]
可以正常使用，从笔记到视频，我是一直点击`booknote2potplayer.exe`出现的提示，不是很明白，这个回链是怎么进行的。。

**Comment by livelycode36** [comment]
> 可以正常使用，从笔记到视频，我是一直点击`booknote2potplayer.exe`出现的提示，不是很明白，这个回链是怎么进行的。。

这个exe是给windows调用的，你点击就会提示`请提供至少一个参数`

如果你的 `视频 --> 笔记`没有问题
那么，如果让`笔记回链-->视频`，只用点击install.bat即可

不过你可以先不用，我晚点再发一版，会有截图、时间调整、是否暂停，而且会调整一下回链的协议，目前使用会不兼容
到时候，在ob中也可以使用快捷键，就不用切换到potplayer了

**Comment by YIRU69** [comment]
感谢大大🎉
很好用！！！

**Comment by YIRU69** [comment]
@livelycode36 回链的链接文字能否别转码，希望显示出中文英文

**Comment by livelycode36** [comment]
> @livelycode36 回链的链接文字能否别转码，希望显示出中文英文

我懂你的意思，在obsidian的编辑状态下不转码，可以看到视频的路径。但是这样有一个缺点，也就是在编辑状态下，不可以跳转到potplayer，只能在阅读模式下跳转到potplayer，这样，我加一个开关，你自行选择是否开启转码

**Comment by YIRU69** [comment]
> > @livelycode36 回链的链接文字能否别转码，希望显示出中文英文
> 
> 我懂你的意思，在obsidian的编辑状态下不转码，可以看到视频的路径。但是这样有一个缺点，也就是在编辑状态下，不可以跳转到potplayer，只能在阅读模式下跳转到potplayer，这样，我加一个开关，你自行选择是否开启转码

明白了，能否完成不转码也可以跳转到pot，跳转连接进行跳转前，识别到链接进行转码再进行下一步可以吗

**Comment by livelycode36** [comment]
> > > @livelycode36 回链的链接文字能否别转码，希望显示出中文英文
> > 
> > 
> > 我懂你的意思，在obsidian的编辑状态下不转码，可以看到视频的路径。但是这样有一个缺点，也就是在编辑状态下，不可以跳转到potplayer，只能在阅读模式下跳转到potplayer，这样，我加一个开关，你自行选择是否开启转码
> 
> 明白了，能否完成不转码也可以跳转到pot，跳转连接进行跳转前，识别到链接进行转码再进行下一步可以吗

好主意，一会更新

**Comment by YIRU69** [comment]
请问一下，我使用你的新版本，出现获取的时间是不是时间格式，就是一个数字，比如
`[36](jv://seek?path=D%3A%5CMybase%5C700-Extras%5C.720-Video%5CJavaScript%E8%AF%BE%E7%A8%8B-Jonas%20Schmedtmann%5C%5BP001%5D001%20Course%20Structure%20and%20Projects.mp4&time=36)`
实际时间是00:04:48 最前面的一个版本是对的呀 显示的是
`00:24:36.320`这种

**Comment by livelycode36** [comment]
实际上time的格式`36`(秒)、`04:48`、`288`(秒)、`00:04:48`、`00:24:36.320`，potplayer都支持跳转。
倒是我的版本一直都是`36`(秒)、`04:48`(分:秒)、`01:04:18`(时:分:秒)这种格式才对

**Comment by YIRU69** [comment]
我想应该是，在potplayer通过快捷键获取的时间是这个格式，我查查怎么可以自己更改这个格式

**Comment by livelycode36** [comment]
> 我想应该是，在potplayer通过快捷键获取的时间是这个格式，我查查怎么可以自己更改这个格式

快捷键G手动定位，会有`00:00:10.198`该类型的时间戳，其实我也可以在只有秒的时候，补齐分钟，例如`00:36`

**Comment by YIRU69** [comment]
是的，我以前自己设计的quicker动作，就是利用快捷键G手动定位的时间，所以突然变了格式，以前的笔记都要改，还没有找到怎么更改这个时间格式。。。

**Comment by YIRU69** [comment]
找到了！
![image](https://github.com/livelycode36/obsidian2potplayer/assets/48148292/2afcb09d-b093-433d-b98e-377d7a33e719)

**Comment by livelycode36** [comment]
干得漂亮！
