### ISSUE TITLE
本地视频，做视频笔记时，尝试点击时间戳报错：PotPlayer is not running

### ISSUE THREAD

**Issue by mdsnalw** [livelycode36/markdown2potplayer#20]
软件端设置：markdown2potplayer软件端的设置（无特殊设置）：
![image](https://github.com/livelycode36/markdown2potplayer/assets/57386018/4134e075-a056-4d9a-b6a5-40012fd8be26)

不知道是否有PotPlayer路径上级文件夹不能有空格的要求？

1. 视频时间戳和图片截图获取都正常. 
2. 点击时间戳回放时报错：PotPlayer is not running （是不是可以理解成正在运行中？ Potplayer is now running）
3. 关掉Potplayer, 直接点击回链，能正常打开PotPlayer, 并跳转到指定时间戳
4. 以下弹窗报错，只会在Potlayer做时间戳笔记，点击时间戳时出现. 

软件弹窗提示：
![image](https://github.com/livelycode36/markdown2potplayer/assets/57386018/d6a6f2b6-a501-403a-a6ae-9bad00d518c7)

提前谢谢大佬~~

**Comment by livelycode36** [comment]
稳定触发这个bug吗？我这边一切正常没有复现，方便录制个视频吗？你可以脱敏新建一个库，我瞅瞅

**Comment by mdsnalw** [comment]
是稳定复现的哦，我随便下载了一个视频，然后本地播放，在大时间戳，已经打开potplayer的情况下，点击时间戳就会出现这样的报错：
![image](https://github.com/livelycode36/markdown2potplayer/assets/57386018/9970f095-2279-4cd7-9ddd-0e313a27c744)
这么看来，应该跟文件名或目录的格式关系不大. 
播放的本地视频：
![image](https://github.com/livelycode36/markdown2potplayer/assets/57386018/3336d21e-9acb-49f7-b92f-7aa01fc0f16b)

测试库已经打包如附件：
[markdown2Potplayer.zip](https://github.com/livelycode36/markdown2potplayer/files/14761244/markdown2Potplayer.zip)

**Comment by livelycode36** [comment]
https://github.com/livelycode36/markdown2potplayer/assets/57926220/a94b9f61-6078-4cee-aa6b-76e87be81439

太怪了哥们，我这真没发现这个bug，要不你留个联系方式吧

**Comment by mdsnalw** [comment]
可以的哈，我回邮件给你

**Comment by mdsnalw** [comment]
大佬，留个邮箱哈，我发微信 ID 给你



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年03月27日 01:34 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [livelycode36/markdown2potplayer] 本地视频，做视频笔记时，尝试点击时间戳报错：PotPlayer is not running (Issue #20) |

https://github.com/livelycode36/markdown2potplayer/assets/57926220/a94b9f61-6078-4cee-aa6b-76e87be81439

太怪了哥们，我这真没发现这个bug，要不你留个联系方式吧

**Comment by livelycode36** [comment]
radio36@qq.com
