### ISSUE TITLE
功能异常 

### ISSUE THREAD

**Issue by maru7777** [livelycode36/markdown2potplayer#21]
获取窗口句柄异常?
以管理员运行后情况依旧
日志:
Error: Target control not found.

▶	1327: Return PostMessage(msg_type,wParam,lParam,hwnd)

Call stack:
*#1 (1327) : [PostMessage] Return PostMessage(msg_type,wParam,lParam,hwnd)
*#1 (1327) : [PotplayerControl.Prototype.PostCommand] Return PostMessage(msg_type,wParam,lParam,hwnd)
*#1 (1347) : [PotplayerControl.Prototype.GetMediaPathToClipboard] this.PostCommand(this.COMMAND_TYPE,10928,0)
*#1 (2201) : [PressDownHotkey] operate_potplayer(potplayer_control)
*#1 (2190) : [GetMediaPath] Return PressDownHotkey(potplayer_control.GetMediaPathToClipboard)
*#1 (2165) : [Potplayer2Obsidian] media_path := GetMediaPath()
> !g Up

**Comment by livelycode36** [comment]
0.2.4版本，试了一下，没问题啊？？？考虑到是不是，您不是x64的版本？
- potplayer的下载地址：[Global Potplayer](https://potplayer.daum.net/) **下载x64的版本**

**Comment by maru7777** [comment]
> 0.2.4版本，试了一下，没问题啊？？？考虑到是不是，您不是x64的版本？
> 
> * potplayer的下载地址：[Global Potplayer](https://potplayer.daum.net/) **下载x64的版本**

的确从32位换到64位后问题消失了 原因出在我使用的是老版本的32位程序
不过发现一个新问题 比如我在3分25秒设置了一个时间戳,但单击这个时间戳却跳转到了3分18秒 
或者是点击3分49秒的时间戳却跳到3分45秒 
滞后的时间不固定

**Comment by livelycode36** [comment]
这个是potplayer对时间的后处理的问题，可以参考[potplayer快捷控制](https://github.com/livelycode36/markdown2potplayer#potplayer%E5%BF%AB%E6%8D%B7%E6%8E%A7%E5%88%B6)：`前进、后退精确到秒`，关掉potplayer对时间的后处理

**Comment by maru7777** [comment]
> 这个是potplayer对时间的后处理的问题，可以参考[potplayer快捷控制](https://github.com/livelycode36/markdown2potplayer#potplayer%E5%BF%AB%E6%8D%B7%E6%8E%A7%E5%88%B6)：`前进、后退精确到秒`，关掉potplayer对时间的后处理

感谢作者,问题已经完美解决
