### ISSUE TITLE
希望增加 回链写入当前字幕功能，并支持自定义字幕和回链的顺序

### ISSUE THREAD

**Issue by C21H21NO2S** [livelycode36/markdown2potplayer#22]
如题，pp 复制当前字幕到剪切板 的快捷键要自定义

![image](https://github.com/user-attachments/assets/2700d8f6-a00b-469c-8f6b-78d4fd0ee8da)

**Comment by livelycode36** [comment]
ok~安排！

> 复制当前字幕到剪切板 的快捷键要自定义
意思是
1. 增加 回链写入当前字幕功能，并支持自定义字幕和回链的顺序
2. 自定义 复制当前字幕到剪切板的**快捷键**？

**Comment by C21H21NO2S** [comment]
> ok~安排！
> 
> > 复制当前字幕到剪切板 的快捷键要自定义
> > 意思是
> 
> 1. 增加 回链写入当前字幕功能，并支持自定义字幕和回链的顺序
> 2. 自定义 复制当前字幕到剪切板的**快捷键**？

cool，第二点随意，能实现当前字幕写入到笔记就行 😋

**Comment by livelycode36** [comment]
感冒了一周，真是难顶，弄的有点晚，哥们得空，试一试？
[0.2.5-beta1](https://github.com/livelycode36/markdown2potplayer/releases/tag/0.2.5-beta1)

**Comment by C21H21NO2S** [comment]
> 感冒了一周，真是难顶，弄的有点晚，哥们得空，试一试？ [0.2.5-beta1](https://github.com/livelycode36/markdown2potplayer/releases/tag/0.2.5-beta1)

非常感谢，多谢了，已经可以用。有些修改建议，麻烦大佬看看：
1. 时间戳和字幕的格式希望支持这样：
 `[00:01:50](link) 字幕XXXX`
2. 独立的字幕回链模板，添加字幕不一定是必需的。

PS: 佬，注意多休息 ❤

**Comment by livelycode36** [comment]
好像`[00:01:50](link) 字幕XXXX`
![image](https://github.com/user-attachments/assets/5992672b-a3a5-4f3e-837b-31c072c55a71)
这样搭配是可以做到这个效果的，**你的意思是在 `字幕模板`中这样`[{time}](link) 字幕xxx`使用是吗？**
还是像`回链模板(Alt+G)`这样的吗？

我感觉你这个功能像是 把srt这种字幕文件，转为 回链？

**Comment by C21H21NO2S** [comment]
> 好像`[00:01:50](link) 字幕XXXX` ![image](https://private-user-images.githubusercontent.com/57926220/355862219-5992672b-a3a5-4f3e-837b-31c072c55a71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNDI2NTQsIm5iZiI6MTcyMzA0MjM1NCwicGF0aCI6Ii81NzkyNjIyMC8zNTU4NjIyMTktNTk5MjY3MmItYTNhNS00ZjNlLTgzN2ItMzFjMDcyYzU1YTcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDE0NTIzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwNjRkOTM3ODA1MWVjOWY3ZDE4N2QyZTZmOTllN2Q0Y2FmMDYwODliMzY5N2ZlZDk3OTk1OGFmYjBmNTA2ZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k259BwtFeXQkN8vBbsovjcdaeaWlHe3v6UJEgECFkoY) 这样搭配是可以做到这个效果的，**你的意思是在 `字幕模板`中这样`[{time}](link) 字幕xxx`使用是吗？** 还是像`回链模板(Alt+G)`这样的吗？
> 
> 我感觉你这个功能像是 把srt这种字幕文件，转为 回链？

可以了，谢谢解答，原来是自己不会用，hahaha。
批量字幕转回链，我自己写了quicker动作，不过md2pp，感觉也可以添加。有时候是需要单条字幕转回链的，所以提了这个功能需求，不知道能不能跟单时间戳模板分开呢（其实删除添加了的字幕也行，就是多了个步骤 😀）

**Comment by C21H21NO2S** [comment]
@livelycode36 佬，请问还会继续完善吗

**Comment by livelycode36** [comment]
> @livelycode36 佬，请问还会继续完善吗

完善，必须的，我这几天阳了。明天我在搞一搞，你的意思是，搞几个常用的模板进行快速切换是吧

**Comment by C21H21NO2S** [comment]
> > @livelycode36 佬，请问还会继续完善吗
> 
> 完善，必须的，我这几天阳了。明天我在搞一搞，你的意思是，搞几个常用的模板进行快速切换是吧

谢谢，不过不急，大佬先休息好 ☕。在原来的基础上增加一个字幕模板，可自定义快捷键就行。

**Comment by livelycode36** [comment]
[0.2.5-beta2](https://github.com/livelycode36/markdown2potplayer/releases/tag/0.2.5-beta2)

试一试这版，改动较大，帮我测测

**方式1**-模板这里填：`{title} {subtitle}`
![image](https://github.com/user-attachments/assets/db90b3b3-b5a9-4bc9-b5e8-e0c2abf8ec52)

**方式2**-手搓md的链接，模板这里填：`[{time}]({link}) {subtitle}`
![image](https://github.com/user-attachments/assets/16b0b4d4-cd0d-491a-a4e6-49658c62839a)

**Comment by C21H21NO2S** [comment]
> [0.2.5-beta2](https://github.com/livelycode36/markdown2potplayer/releases/tag/0.2.5-beta2)
> 
> 试一试这版，改动较大，帮我测测
> 
> **方式1**-模板这里填：`{title} {subtitle}` ![image](https://private-user-images.githubusercontent.com/57926220/357912809-db90b3b3-b5a9-4bc9-b5e8-e0c2abf8ec52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NTYyMTQsIm5iZiI6MTcyMzY1NTkxNCwicGF0aCI6Ii81NzkyNjIyMC8zNTc5MTI4MDktZGI5MGIzYjMtYjVhOS00YmM5LWI1ZTgtZTBjMmFiZjhlYzUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDE3MTgzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmYmE3ZDJmZWZkM2UzODU1ODhmZDM4OGRhMDBmZmRmOGMwYzNjMjYwZWQ5ZWQ0NmUyYWNkNjQ2ZmU2ODk4N2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CKQX8cdSPjB2HSAMKpOQiU6f5iLljTAHQiuBaIQJtqY)
> 
> **方式2**-手搓md的链接，模板这里填：`[{time}]({link}) {subtitle}` ![image](https://private-user-images.githubusercontent.com/57926220/357913434-16b0b4d4-cd0d-491a-a4e6-49658c62839a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NTYyMTQsIm5iZiI6MTcyMzY1NTkxNCwicGF0aCI6Ii81NzkyNjIyMC8zNTc5MTM0MzQtMTZiMGI0ZDQtY2QwZC00OTFhLWE0ZTYtNDk2NThjNjI4MzlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDE3MTgzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiNDJiZmMzNWIzMzllZjE2MzA1NTY5ZmMyNmM4Y2JiZDA4NDM5YmJiNTk3Y2YwOTgyYzFmZmZiMTYwOGI3N2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qERuXk5tcOcFBf4YKA5jEpStDKWDIqXrLGD5R6BV-_E)

抱歉，今天有点忙，回复晚了。字幕模板已经可以用了，但用的过程中我发现了个瑕疵是我之前没考虑到的，失策了。
瑕疵是：时间戳会比当前字幕的开始时间晚，不知道用“字幕模板”功能的时候，能不能按当前字幕的开始时间插入时间戳呢 😁

**Comment by livelycode36** [comment]
倒也简单，不过要求，srt的字幕文件和视频文件同名称，例如：`test.mp4`和`test.srt`，这样我可以解析srt内的时间

**Comment by livelycode36** [comment]
试试这个，[0.2.5-beta3](https://github.com/livelycode36/markdown2potplayer/releases/tag/0.2.5-beta3)

srt的字幕文件和视频文件同名称，例如：`test.mp4`和`test.srt`

另外加入了 **srt字幕转md**
![image](https://github.com/user-attachments/assets/6e940938-f544-42e6-997f-a795c05d0f1d)

**Comment by C21H21NO2S** [comment]
> 试试这个，[0.2.5-beta3](https://github.com/livelycode36/markdown2potplayer/releases/tag/0.2.5-beta3)
> 
> srt的字幕文件和视频文件同名称，例如：`test.mp4`和`test.srt`
> 
> 另外加入了 **srt字幕转md** ![image](https://private-user-images.githubusercontent.com/57926220/358313997-6e940938-f544-42e6-997f-a795c05d0f1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4NjA2MDEsIm5iZiI6MTcyMzg2MDMwMSwicGF0aCI6Ii81NzkyNjIyMC8zNTgzMTM5OTctNmU5NDA5MzgtZjU0NC00MmU2LTk5N2YtYTc5NWMwNWQwZjFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE3VDAyMDUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1OTZjMzliNjA4ZTliN2RhNWE0MzA1ZDI4NjY5MzFiNWZlYjU4NDc5ZjBiNjgwZGY5MTdkYzhlYzMzYzlmMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hyr5HI6NYIiJ09H8fQ6QVRpVVksT7q8vhelVCucOUTE)

抱歉，突然发现这个功能其实有挺多细节要考虑的。如：
1. pp内用双击字幕浏览器内的字幕来定位后，用alt+t  字幕模板，插入的是上一条字幕；
2. 字幕模板有时候不需要区间播放；
3. 我试了srt2md，单 双语字幕的中文字幕会变成乱码。

**Comment by livelycode36** [comment]
1. 应该是potplayer中的字幕显示比实际慢，可以采用srt内的字幕
2. 不需要区间播放，可以读取srt中的开始时间即可
3. 这个双语字幕中文为啥会乱码？？字幕文件分享一下，我看看（srt可能不是GBK编码的问题吧？）字幕比较隐私的话，可以加我

**Comment by C21H21NO2S** [comment]
> 1. 应该是potplayer中的字幕显示比实际慢，可以采用srt内的字幕
> 2. 不需要区间播放，可以读取srt中的开始时间即可
> 3. 这个双语字幕中文为啥会乱码？？字幕文件分享一下，我看看（srt可能不是GBK编码的问题吧？）字幕比较隐私的话，可以加我

1. 是.srt文件，可能是pp用字幕定位也会自动往前一些，不知道能不能兼容一下，因为字幕定位挺实用的——一般步进、步退的时间不会设置1秒的跨度，用了步退还要播放一会才能定位；
3. 中文字幕乱码的原因好像是我用了.lrc，抱歉哈。

**Comment by livelycode36** [comment]
刚才试了一下`字幕浏览器`按 `alt + T`的字幕是准确的呀？？
**有一个情况就是**：有时候点击字幕，potplayer的画面和字幕是卡住不动的，这个时候`alt + T`的字幕是不对的，此时播放一下视频才行

**Comment by C21H21NO2S** [comment]
> 刚才试了一下`字幕浏览器`按 `alt + T`的字幕是准确的呀？？ **有一个情况就是**：有时候点击字幕，potplayer的画面和字幕是卡住不动的，这个时候`alt + T`的字幕是不对的，此时播放一下视频才行

这样的吗，我是暂停后用字幕浏览器跳转的，没有继续播放

**Comment by livelycode36** [comment]
组合一下的话，你字幕模板使用`[{subtitleTimeStart}]({link}) {subtitleOrigin}`应该能达到你要的效果

---

[0.2.5-beta4](https://github.com/livelycode36/markdown2potplayer/releases/tag/0.2.5-beta4)

- `{time}`: 代表 potplayer中的当前时间戳
- `{subtitle}`: 代表 potplayer中的当前字幕
- `{subtitleTimeRange}`: 代表 .str字幕文件中的 开始和结束时间。例如: `01:02-03:04`
- `{subtitleTimeStart}`: 代表 .str字幕文件中的 开始时间。例如: `01:02`
- `{subtitleTimeEnd}`: 代表 .str字幕文件中的 结束时间。例如: `03:04`
- `{subtitleOrigin}`: 代表 .str字幕文件中的 当前时间戳的字幕。例如: `猴哥猴哥，你真了不得`

- 注意: `.srt转md`中的数据格式，受到 `字幕模板` 中的样式进行控制。

**Comment by C21H21NO2S** [comment]
> 组合一下的话，你字幕模板使用`[{subtitleTimeStart}]({link}) {subtitleOrigin}`应该能达到你要的效果
> 
> [0.2.5-beta4](https://github.com/livelycode36/markdown2potplayer/releases/tag/0.2.5-beta4)
> 
> * `{time}`: 代表 potplayer中的当前时间戳
> * `{subtitle}`: 代表 potplayer中的当前字幕
> * `{subtitleTimeRange}`: 代表 .str字幕文件中的 开始和结束时间。例如: `01:02-03:04`
> * `{subtitleTimeStart}`: 代表 .str字幕文件中的 开始时间。例如: `01:02`
> * `{subtitleTimeEnd}`: 代表 .str字幕文件中的 结束时间。例如: `03:04`
> * `{subtitleOrigin}`: 代表 .str字幕文件中的 当前时间戳的字幕。例如: `猴哥猴哥，你真了不得`
> * 注意: `.srt转md`中的数据格式，受到 `字幕模板` 中的样式进行控制。

感谢大佬，有空我测试一下

**Comment by livelycode36** [comment]
> > 组合一下的话，你字幕模板使用`[{subtitleTimeStart}]({link}) {subtitleOrigin}`应该能达到你要的效果
> > [0.2.5-beta4 0.2.5-贝塔4](https://github.com/livelycode36/markdown2potplayer/releases/tag/0.2.5-beta4)
> > 
> > * `{time}`: 代表 potplayer中的当前时间戳
> > * `{subtitle}`: 代表 potplayer中的当前字幕
> > * `{subtitleTimeRange}`: 代表 .str字幕文件中的 开始和结束时间。例如: `01:02-03:04`
> > * `{subtitleTimeStart}`: 代表 .str字幕文件中的 开始时间。例如: `01:02`
> > * `{subtitleTimeEnd}`: 代表 .str字幕文件中的 结束时间。例如: `03:04`
> > * `{subtitleOrigin}`: 代表 .str字幕文件中的 当前时间戳的字幕。例如: `猴哥猴哥，你真了不得`
> > * 注意: `.srt转md`中的数据格式，受到 `字幕模板` 中的样式进行控制。
> 
> 感谢大佬，有空我测试一下

猿神启动！

**Comment by C21H21NO2S** [comment]
> 组合一下的话，你字幕模板使用`[{subtitleTimeStart}]({link}) {subtitleOrigin}`应该能达到你要的效果
> 
> [0.2.5-beta4](https://github.com/livelycode36/markdown2potplayer/releases/tag/0.2.5-beta4)
> 
> * `{time}`: 代表 potplayer中的当前时间戳
> * `{subtitle}`: 代表 potplayer中的当前字幕
> * `{subtitleTimeRange}`: 代表 .str字幕文件中的 开始和结束时间。例如: `01:02-03:04`
> * `{subtitleTimeStart}`: 代表 .str字幕文件中的 开始时间。例如: `01:02`
> * `{subtitleTimeEnd}`: 代表 .str字幕文件中的 结束时间。例如: `03:04`
> * `{subtitleOrigin}`: 代表 .str字幕文件中的 当前时间戳的字幕。例如: `猴哥猴哥，你真了不得`
> * 注意: `.srt转md`中的数据格式，受到 `字幕模板` 中的样式进行控制。

感谢。
* 有一些瑕疵，在双击字幕跳转后，用 `{subtitleTimeStart}` 会识别上一行字幕的时间，即使pp显示的时间是正确的，具体麻烦到老看看下面的视频；
* 用 `{subtitleOrigin}` 会出现乱码，用 `{subtitle}` 才没问题，我附上字幕文件  [02 音名与钢琴键盘.zip](https://github.com/user-attachments/files/16736426/02.zip)；
* 另外，不知道能不能优化一下时间，跟alt+G一样是 `00:11:12:` 这样的格式。

https://github.com/user-attachments/assets/a9653297-3a7c-4505-afcb-8cc591da35f7

**Comment by livelycode36** [comment]
> - 用 `{subtitleTimeStart}` 会识别上一行字幕的时间，即使pp显示的时间是正确的

这个问题的话，其实是和srt的字幕格式有关，因为srt上一个字幕的结尾时间 和 当前字幕的开头时间是一样的
![image](https://github.com/user-attachments/assets/09361068-798f-4eeb-8c50-b51ab8cd797a)

> 用 `{subtitleOrigin}` 会出现乱码，用 `{subtitle}` 才没问题

这个问题的话，默认是使用windows的当前系统的编码GBK，对srt文件进行读取，我看到你的srt文件是utf-8，所以出现了乱码，这个我尝试解决一下

> 能不能优化一下时间，跟`alt+G`一样是 `00:11:12` 这样的格式

srt带毫秒的呀，如果和`alt+G`一样`00:11:12`那不是去掉毫秒了？我斟酌一下
