### ISSUE TITLE
请问能兼容一下Boardmix 网页版吗

### ISSUE THREAD

**Issue by C21H21NO2S** [livelycode36/markdown2potplayer#23]
如题，现在复制到Boardmix 的回链都不能正常打开，协议是：jv://open?path=\\

![image](https://github.com/user-attachments/assets/cadccc4c-7e46-4f96-8c0f-61a8b7ecc950)

**Comment by livelycode36** [comment]
哦？？没用过Boardmix，那你加我一下微信号`GodForChina`吧，我看看这Boardmix是啥玩意
