### ISSUE TITLE
使用PotPlayer的Ctrl+U快捷键粘贴Bilibili视频链接后，提示无法播放（服务器已关闭或地址错误）

### ISSUE THREAD

**Issue by mdsnalw** [livelycode36/markdown2potplayer#24]
做过的操作：
前期准备：
1. 启用obsidian
2. 打开markdown2potplayer软件（已经更新到最新版0.2.5）
3. potplayer部分，也已经将“Bilibili_Config”脚本的Cookies重新粘贴，并且在Potplayer端能正确识别哔哩哔哩账号. 
4. 打开Potplayer，并使用Ctrl+U快捷键呼出对话框，粘贴bilibili视频链接. 
5. 查看播放器界面，其实已经后识别到链接标题，但就是提示报错，无法播放. 

![image](https://github.com/user-attachments/assets/3f3d8811-7791-45fe-ab55-0805ef020514)

6. 相关使用过的链接：
- https://www.bilibili.com/video/BV116HDePEdy
- https://www.bilibili.com/video/BV17Y4ZeDEhZ

**Comment by mdsnalw** [comment]
问题已解决😁, 我尝试用新下载的"MediaPlayParse - Bilibili.as"文件，覆盖Potplayer下的对应同名文件即可. 估计是用旧版的解析会出现问题.

**Comment by livelycode36** [comment]
okk~
