### ISSUE TITLE
FR：对脚本的一些建议

### ISSUE THREAD

**Issue by YIRU69** [livelycode36/markdown2potplayer#4]
作者好，我的一位朋友github 账号丢了，我帮忙转述一下他的建议

1.尽量多个ahk合并成一个exe，后台运行。
2.别用ini设置参数，过于极客。改成设置面板，用户点击或下拉来设置参数
3.其中url_protocol参数是超链接语法头，可以随意指定
但希望点击超链接时支持jv://、jumbvideo://、obsidian://等各种语料前缀，均能按path或url来确定视频路径，time确定时间点，进行播放。
即增加足够强的语法兼容性
4.我测试b站视频的网址中包含?&等符号，与ahk算法代码有冲突，需要规避
5.点击超链接语法后跳转，视频有时暂停，不能保证自动播放，需要修正。
6.建议增加历史记录功能，如打开过的文件夹或视频存成列表，方便用户回看。

**Comment by YIRU69** [comment]
另外他想私下联系你 看你方便吗

**Comment by livelycode36** [comment]
1、2、3、4已完成

`5`我这里没有复现

`6`历史记录得看potplayer，有没有对应的接口啊(`好像有`)，不然只能外挂一个列表，这就又和UI画面相关了

**Comment by livelycode36** [comment]
> 另外他想私下联系你 看你方便吗

那就发个联系方式吧，我加一下，wx常用，qq不咋用

**Comment by YIRU69** [comment]
我提供一下qq 312815311 @livelycode36

**Comment by livelycode36** [comment]
okok，这两天有点忙，闲下来就加，稍等稍等

**Comment by YIRU69** [comment]
> `1`、`2`的话，得需要UI界面，autohotkey不太熟，而且我也不太会画UI页面，有生之年吧，对于配置的说明，文档还是应该清楚的吧，凑活一下。

对于这个我提供一下，类似的项目，可以供你参考，https://github.com/flyinclouds/KBLAutoSwitch 这个项目我一直在用
