### ISSUE TITLE
FR: 增加AB区间和AB循环功能

### ISSUE THREAD

**Issue by YIRU69** [livelycode36/markdown2potplayer#6]
作者大大，可以增加AB区间和AB循环功能吗？

**Comment by livelycode36** [comment]
好啊，不过
在考虑，是2种形态的回链？
- 固定播放一次
- 可调次数的播放

还是固定1种形态？
- 可调次数的播放

兄弟给点意见？

**Comment by YIRU69** [comment]
我建议一个单次播放，一个单次循环，次数好像没必要

**Comment by livelycode36** [comment]
嗯嗯，可以

**Comment by livelycode36** [comment]
搞定了，辛苦试用下看看有bug没

**Comment by YIRU69** [comment]
我大概测试了一下，工作完美！

有一个小的不足，就是默认的 F2 快捷键是重命名的快捷键，可以换一个

这个可以自己改的，问题不大
