### ISSUE TITLE
关于SendMessage入参是怎么获得的

### ISSUE THREAD

**Issue by WillemLiao** [livelycode36/markdown2potplayer#7]
作者好，我是小白，我想问一下比如获取播放视频向SendMessage传的参数是这三个
![image](https://github.com/livelycode36/markdown2potplayer/assets/12184000/c169b270-5fe8-4ada-b7bb-5081414d1029)
设置视频AB点传的参数是这三个
![image](https://github.com/livelycode36/markdown2potplayer/assets/12184000/581b8be8-7f9f-4f8e-bdc2-bf9917c0b0ee)
hwnd 这个值我知道怎么获得，其他三个值如何获得，是通过什么工具吗，可以指点一下嘛？

**Comment by livelycode36** [comment]
剩下3个参数可以使用[westoncampbell/SpyPlusPlus:Spy++](https://github.com/westoncampbell/SpyPlusPlus)进行获取
