### ISSUE TITLE
BUG: 循环片段必须要打开 potplayer 才能运行

### ISSUE THREAD

**Issue by YIRU69** [livelycode36/markdown2potplayer#8]
在使用的过程中，发现循环的片段必须要先打开 potplayer , 不然就报错，如图

![image](https://github.com/livelycode36/markdown2potplayer/assets/48148292/3592734b-eaf8-4f94-b598-81d8dd1f36e9)

时间格式为`[Z](jv://open?path=D:\Mybase\700-Extras\.720-Video\How%20to%20write%20English%20capital%20and%20small%20letters%20-%20Cursive%20writing%20a%20to%20z-%20Cursive%20abcd%20-%20letters%20abcd.mp4&time=00:12:32.665∞00:12:48.7)` 

不循环，跳转是正常的。

另外提出一个建议，希望在软件界面加上版本号。

**Comment by YIRU69** [comment]
还是一个问题，是暗模式的界面 css 好像有问题
![image](https://github.com/livelycode36/markdown2potplayer/assets/48148292/fdc1d1ac-c88a-47b1-a409-ffe8c4571136)

**Comment by livelycode36** [comment]
1. 跳转修复了
2. 版本号在标题
3. 暗黑模式嘛，UI我是用Auto-GUI-v2还没研究明白，不过平时也不用怎么打开界面，暂时将就一下😄

**Comment by YIRU69** [comment]
谢谢，👍
